name: strapi-cron-job
'on':
  schedule:
    - cron: 35 12 * * 1
    - cron: 40 12 * * 1
    - cron: 45 12 * * 1
  workflow_dispatch: null
jobs:
  stg_jobs_api:
    if: ${{ github.event.schedule == '35 12 * * 1' }}
    runs-on: ubuntu-latest
    # environment: strapi-staging
    steps:
      - name: Check out the repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo GitHub event_name and schedule
        run: |
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub event.schedule: ${{ github.event.schedule }}"
      - name: Get request to the custom Strapi route
        run: |
          curl -vs https://brand-onesite-cms-strapi-stg-v4xn3wfs6a-ew.a.run.app/api/cron/jobs
  stg_clear_stale_jobs:
    if: ${{ github.event.schedule == '40 12 * * 1' }}
    runs-on: ubuntu-latest
    # environment: strapi-staging
    steps:
      - name: Check out the repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo GitHub event_name and schedule
        run: |
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub event.schedule: ${{ github.event.schedule }}"
      - name: Get request to the custom Strapi route
        run: |
          curl -vs https://brand-onesite-cms-strapi-stg-v4xn3wfs6a-ew.a.run.app/api/cron/clear-stale/jobs
  stg_clear_stale_auditlogs:
    if: ${{ github.event.schedule == '45 12 * * 1' }}
    runs-on: ubuntu-latest
    # environment: strapi-staging
    steps:
      - name: Check out the repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo GitHub event_name and schedule
        run: |
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub event.schedule: ${{ github.event.schedule }}"
      - name: Get request to the custom Strapi route
        run: |
          curl -vs https://brand-onesite-cms-strapi-stg-v4xn3wfs6a-ew.a.run.app/api/cron/clear-stale/auditlogs
  # prd_jobs_api:
  #   if: ${{ github.event.schedule == '0 1 * * 0' }}
  #   runs-on: ubuntu-latest
  #   environment: strapi-production
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Echo GitHub event_name and schedule
  #       run: |
  #         echo "GitHub event_name: ${{ github.event_name }}"
  #         echo "GitHub event.schedule: ${{ github.event.schedule }}"
  #     - name: Get request to the custom Strapi route
  #       run: |
  #         curl -vs https://${{vars.FE_URL}}/api/cron/jobs
  # prd_clear_stale_auditlogs:
  #   if: ${{ github.event.schedule == '0 1 * * 1/2' }}
  #   runs-on: ubuntu-latest
  #   environment: strapi-production
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Echo GitHub event_name and schedule
  #       run: |
  #         echo "GitHub event_name: ${{ github.event_name }}"
  #         echo "GitHub event.schedule: ${{ github.event.schedule }}"
  #     - name: Get request to the custom Strapi route
  #       run: |
  #         curl -vs https://brand-onesite-cms-strapi-stg-v4xn3wfs6a-ew.a.run.app/
  # prod_clear_stale_jobs:
  #   if: ${{ github.event.schedule == '0 6 * * 0' }}
  #   runs-on: ubuntu-latest
  #   environment: strapi-production
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Echo GitHub event_name and schedule
  #       run: |
  #         echo "GitHub event_name: ${{ github.event_name }}"
  #         echo "GitHub event.schedule: ${{ github.event.schedule }}"
  #     - name: Get request to the custom Strapi route
  #       run: |
  #         curl -vs https://${{vars.FE_URL}}/api/cron/clear-stale/jobs
