name: strapi-cron-job
'on':
  schedule:
    - cron: '*/1 * * * *'
    - cron: '*/2 * * * *'
  workflow_dispatch: null
jobs:
  jobsApi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo GitHub event_name and schedule
        run: |
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub event.schedule: ${{ github.event.schedule }}"
          echo "GitHub event.ref: ${{ github.ref }}"
      - name: Get request to the custom Strapi route
        run: >
          echo "Executing curl command"

          response=$(curl -vs
          https://webhook.site/8da87bfa-ef79-438d-a2d8-168eb0778955 2>&1)
          echo "response from curl= $response"
  jobsApi2:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/1 * * * *' && github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Echo GitHub event_name and schedule
        run: |
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub event.schedule: ${{ github.event.schedule }}"
      - name: Get request to the custom Strapi route
        run: >
          echo "Executing curl command"

          response=$(curl -vs
          https://webhook.site/8da87bfa-ef79-438d-a2d8-168eb0778955 2>&1)

          echo "response from curl= $response"
